name: "create-harbor-project"

on:
  workflow_call:
    inputs:
      api-endpoint:
        description: "The API endpoint of the Harbor container image registry instance (typically just the domain name)"
        type: string
        required: true
      project:
        description: "A new project name within the Harbor container image registry instance"
        type: string
        required: true
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true
      PA_TOKEN:
        required: true

jobs:
  create-new-project:
    runs-on: ubuntu-22.04
    env:
      MANIFEST_YML: ./new-project.yml

    steps:
    - uses: actions/checkout@v4

    - name: Write manifest for new Harbor project
      env:
        NEW_HARBOR_PROJECT: ${{ inputs.project }}
      run: |
        echo "kind: project/CreateProjectParams" > $MANIFEST_YML
        echo "apiVersion: v1alpha1" >> $MANIFEST_YML
        echo "spec:" >> $MANIFEST_YML
        echo "  xresourcenameinlocation: false" >> $MANIFEST_YML
        echo "  project:" >> $MANIFEST_YML
        echo "    projectname: \"$NEW_HARBOR_PROJECT\"" >> $MANIFEST_YML
        echo "    public: true" >> $MANIFEST_YML

    - name: Create new Harbor project
      env:
        HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
        HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        HARBOR_API_ENDPOINT: ${{ inputs.api-endpoint }}
        GH_TOKEN: ${{ secrets.PA_TOKEN }}
      run: |
        gh release download -R hinyinlam/cli-for-harbor -p '*Linux_x86_64.tar.gz' --skip-existing
        tar xvf *Linux_x86_64.tar.gz
        DECODED_HARBOR_PASSWORD=$(echo "$HARBOR_PASSWORD" | base64 -d)
        ./harbor login --username $HARBOR_USERNAME --password $DECODED_HARBOR_PASSWORD --url "https://$HARBOR_API_ENDPOINT"
        set -x
        ./harbor project create --filename $MANIFEST_YML
        ./harbor project list
