name: "create-harbor-project"

on:
  workflow_call:
    inputs:
      api-endpoint:
        description: "The API endpoint of the Harbor container image registry instance (typically just the domain name)"
        type: string
        required: true
      project:
        description: "A new project name within the Harbor container image registry instance"
        type: string
        required: true
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true

jobs:
  create-new-project:
    runs-on: ubuntu-22.04
    env:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_API_ENDPOINT: ${{ inputs.api-endpoint }}
      NEW_HARBOR_PROJECT: ${{ inputs.project }}
      HARBOR_CLI_RELEASE: "v0.0.4"

    steps:
    - uses: actions/checkout@v4

    - name: Create new Harbor project
      run: |
        wget https://github.com/hinyinlam/cli-for-harbor/releases/download/${HARBOR_CLI_RELEASE}/cli-for-harbor_${HARBOR_CLI_RELEASE}_Linux_x86_64.tar.gz
        tar xvf cli-for-harbor_${HARBOR_CLI_RELEASE}_Linux_x86_64.tar.gz
        DECODED_HARBOR_PASSWORD=$(echo "$HARBOR_PASSWORD" | base64 -d)
        harbor login --username $HARBOR_USERNAME --password $DECODED_HARBOR_PASSWORD --url "https://$HARBOR_API_ENDPOINT"
        set -x
        cat <<EOF > new-project.yml
        kind: project/CreateProjectParams
        apiVersion: v1alpha1
        spec:
          xresourcenameinlocation: false
          project:
            projectname: "tanzu"
            public: true
        EOF
        harbor project create --filename new-project.yml
        harbor project list
