name: "prepare-metadata-store-secrets"

on:
  workflow_call:
    inputs:
      cluster-provider:
        description: "The Kubernetes service provider"
        type: string
        required: true
    secrets:
      GOOGLE_PROJECT_ID:
        required: false
      GOOGLE_SERVICE_ACCOUNT_KEY:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_SESSION_TOKEN:
        required: false
      AZURE_AD_CLIENT_ID:
        required: false
      AZURE_AD_CLIENT_SECRET:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      AZURE_AD_TENANT_ID:
        required: false
      TAP_BUILD_KUBECONFIG_CONTENTS:
        required: true
      TAP_VIEW_KUBECONFIG_CONTENTS:
        required: true

jobs:
  encode-prepare-metadata-store-secrets-script:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    outputs:
      result: ${{ steps.encode.outputs.result }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: clicktruck/scripts
    - name: Encode
      id: encode
      run: |
        result="$(cat prepare-metadata-store-secrets.sh | base64 -w 0)"
        echo "result=${result}" >> $GITHUB_OUTPUT

  prepare:
    needs: encode-prepare-metadata-store-secrets-script
    runs-on: ubuntu-22.04

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout azure-actions
      if: inputs.cluster-provider == 'aks'
      uses: actions/checkout@v4
      with:
        repository: clicktruck/azure-actions
        path: runnable

    - name: Checkout aws-actions
      if: inputs.cluster-provider == 'eks'
      uses: actions/checkout@v4
      with:
        repository: clicktruck/aws-actions
        path: runnable

    - name: Checkout google-actions
      if: inputs.cluster-provider == 'gke'
      uses: actions/checkout@v4
      with:
        repository: clicktruck/google-actions
        path: runnable

    - name: "Prepare metadata-store secrets on AKS"
      if: inputs.cluster-provider == 'aks'
      uses: ./runnable/docker/actions/azure/tanzu-runsh-setup-action
      with:
        script-contents: ${{ needs.encode-prepare-metadata-store-secrets-script.outputs.result }}
        script-arguments: ${{ secrets.TAP_VIEW_KUBECONFIG_CONTENTS }} ${{ secrets.TAP_BUILD_KUBECONFIG_CONTENTS }}
        azure-ad-client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        azure-ad-client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}

    - name: "Prepare metadata-store secrets on EKS"
      if: inputs.cluster-provider == 'eks'
      uses: ./runnable/docker/actions/aws/tanzu-runsh-setup-action
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        script-contents: ${{ needs.encode-prepare-metadata-store-secrets-script.outputs.result }}
        script-arguments: ${{ secrets.TAP_VIEW_KUBECONFIG_CONTENTS }} ${{ secrets.TAP_BUILD_KUBECONFIG_CONTENTS }}

    - name: "Prepare metadata-store secrets on GKE"
      if: inputs.cluster-provider == 'gke'
      uses: ./runnable/docker/actions/google/tanzu-runsh-setup-action
      with:
        google-project-id: ${{ secrets.GOOGLE_PROJECT_ID }}
        google-service-account-key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        script-contents: ${{ needs.encode-prepare-metadata-store-secrets-script.outputs.result }}
        script-arguments: ${{ secrets.TAP_VIEW_KUBECONFIG_CONTENTS }} ${{ secrets.TAP_BUILD_KUBECONFIG_CONTENTS }}
