name: "prepare-metadata-store-secrets-dispatch"

on:
  workflow_dispatch:
    inputs:
      cluster-provider:
        description: "The Kubernetes service provider"
        type: choice
        required: true
        options:
          - eks
          - aks
          - gke
      b64-tap-build-cluster-kubeconfig-contents:
        description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set. (You should be targeting a cluster with the Build profile installed)."
        required: true
      b64-tap-view-cluster-kubeconfig-contents:
        description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set. (You should be targeting a cluster with the View profile installed)."
        required: true


jobs:

  prepare-metadata-store-secrets-on-aws:
    if: github.event.inputs.cluster-provider == 'eks'
    uses: ./.github/workflows/prepare-metadata-store-secrets.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TAP_BUILD_KUBECONFIG_CONTENTS: ${{ github.event.inputs.b64-tap-build-cluster-kubeconfig-contents }}
      TAP_VIEW_KUBECONFIG_CONTENTS: ${{ github.event.inputs.b64-tap-view-cluster-kubeconfig-contents }}

  prepare-metadata-store-secrets-on-azure:
    if: github.event.inputs.cluster-provider == 'aks'
    uses: ./.github/workflows/prepare-metadata-store-secrets.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      TAP_BUILD_KUBECONFIG_CONTENTS: ${{ github.event.inputs.b64-tap-build-cluster-kubeconfig-contents }}
      TAP_VIEW_KUBECONFIG_CONTENTS: ${{ github.event.inputs.b64-tap-view-cluster-kubeconfig-contents }}

  prepare-metadata-store-secrets-on-google:
    if: github.event.inputs.cluster-provider == 'gke'
    uses: ./.github/workflows/prepare-metadata-store-secrets.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      TAP_BUILD_KUBECONFIG_CONTENTS: ${{ github.event.inputs.b64-tap-build-cluster-kubeconfig-contents }}
      TAP_VIEW_KUBECONFIG_CONTENTS: ${{ github.event.inputs.b64-tap-view-cluster-kubeconfig-contents }}