name: "uninstall-tanzu-data-services-repo-dispatch"

on:
  workflow_dispatch:
    inputs:
      cluster-provider:
        description: "The Kubernetes service provider"
        required: true
        type: choice
        options:
          - eks
          - aks
          - gke
      kubeconfig-contents:
        description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
        required: true

jobs:
  uninstall-tanzu-data-services-repo-on-azure:
    if: contains(fromJson('["aks"]'), github.event.inputs.cluster-provider)
    uses: ./.github/workflows/uninstall-tanzu-data-services-repo.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}

  uninstall-tanzu-data-services-repo-on-aws:
    if: contains(fromJson('["eks"]'), github.event.inputs.cluster-provider)
    uses: ./.github/workflows/uninstall-tanzu-data-services-repo.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}

  uninstall-tanzu-data-services-repo-on-gke:
    if: github.event.inputs.cluster-provider == 'gke'
    uses: ./.github/workflows/uninstall-tanzu-data-services-repo.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}
